### PR TITLE
[fix]fieldservice_account : fix relation between fsm_order and invoice_line

### PR DESCRIPTION
**Pull request by hparfr**
implement https://github.com/OCA/field-service/issues/628

### CODE REVIEW

**Comment by bodedra** [comment]
@hparfr you have changed field structure, it may impact on migration. So how would you manage it?

**Comment by bodedra** [comment]
@hparfr may you provide migration script?

**Comment by hparfr** [comment]
Hi @bodedra 

Didn't had time to address it yet. Sadly there was none when fsm_order_ids became fsm_order_id. So I have to go figure out how to do it :-)

**Comment by hparfr** [comment]
Hi @bodedra 

Migration script added !

**Review by bodedra — APPROVED** [review]
LG :+1:

**Pull request merged**
